services:
  app:
    image: nocobase/nocobase:latest-full
    restart: always
    environment:
      - APP_KEY=${APP_KEY:-please-generate-with-openssl-rand-hex-32}
      - DB_DIALECT=postgres
      - DB_HOST=${DB_HOST:-your-db-host}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-nocobase}
      - DB_USER=${DB_USER:-nocobase}
      - DB_PASSWORD=${DB_PASSWORD:-changeme}
      - TZ=Asia/Shanghai
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - '13000:80'
